//! TEE + ZK Verifier Contract
//!
//! Soroban smart contract that verifies UltraHonk ZK proofs using
//! Protocol 26 BN254 host functions (g1_msm, g1_add, pairing_check).
//!
//! ## Flow
//!   1. open() — trader deposits collateral against a Poseidon2 commitment
//!   2. close() — trader presents nullifier + UltraHonk proof → gets collateral back
//!
//! ## UltraHonk Verification
//! The proof contains BN254 curve points that encode the Plonk verification
//! equation. The contract uses three Protocol 26 host functions:
//!   - g1_msm:  multi-scalar multiplication on G1
//!   - g1_add:  G1 point addition
//!   - pairing_check: final verification of 4 pairings
//!
//! ## Reference
//! Full UltraHonk Soroban verifier implementation:
//!   https://github.com/indextree/ultrahonk_soroban_contract
//!
//! This contract follows the same pattern: parse proof, compute verification
//! equation, call pairing_check.

#![no_std]

use soroban_sdk::{
    contract, contractimpl, contracttype,
    crypto::bn254::{Bn254Fr, Bn254G1Affine, Bn254G2Affine},
    Address, Bytes, BytesN, Env, Vec,
};

// ── Verification Key ────────────────────────────────────────────────
// These encode the circuit's constraint system.
// Generated by running: nargo compile && (bb.js UltraHonkBackend)
// in the circuit/ directory.
//
// Replace these with real VK values from `nargo compile`.
//
// G1 points: 64 bytes  = big-endian X (32) || Y (32)
// G2 points: 128 bytes = big-endian X.im (32) || X.re (32) || Y.im (32) || Y.re (32)

const VK_ALPHA_G1: [u8; 64] = [0u8; 64];
const VK_BETA_G2: [u8; 128] = [0u8; 128];
const VK_GAMMA_G2: [u8; 128] = [0u8; 128];
const VK_DELTA_G2: [u8; 128] = [0u8; 128];

// IC = input contribution points (Groth16 style)
// UltraHonk uses a different structure, but the BN254 host functions
// are the same primitives. See indextree verifier for full UltraHonk impl.
const VK_IC_0: [u8; 64] = [0u8; 64];
const VK_IC_1: [u8; 64] = [0u8; 64];
const VK_IC_2: [u8; 64] = [0u8; 64];

// ── Storage ─────────────────────────────────────────────────────────

#[contracttype]
pub enum DataKey {
    Position(BytesN<32>),
    Nullifier(BytesN<32>),
}

#[contracttype]
#[derive(Clone)]
pub struct Position {
    pub collateral: i128,
    pub trader: Address,
}

#[contracttype]
pub struct UltraHonkProof {
    // UltraHonk proof contains multiple G1/G2 points and field elements.
    // Exact structure depends on the proving system version.
    // See indextree/ultrahonk_soroban_contract for reference implementation.
    pub proof_bytes: Bytes,
}

// ── Contract ────────────────────────────────────────────────────────

#[contract]
pub struct StellarVerifier;

#[contractimpl]
impl StellarVerifier {
    /// Open a private position.
    ///
    /// `commitment` = Poseidon2([amount, direction, entry_price, salt])
    ///   computed off-chain by the Noir circuit.
    ///
    /// The contract stores only the 32-byte hash. The actual trade details
    /// never appear on-chain.
    pub fn open(
        env: Env,
        trader: Address,
        commitment: BytesN<32>,
        collateral: i128,
    ) {
        trader.require_auth();
        if collateral <= 0 {
            panic!("collateral must be positive");
        }
        let key = DataKey::Position(commitment);
        if env.storage().persistent().has(&key) {
            panic!("commitment already exists");
        }
        env.storage()
            .persistent()
            .set(&key, &Position { collateral, trader });
        env.storage().persistent().extend_ttl(&key, 17280, 17280);
    }

    /// Close a position by presenting an UltraHonk ZK proof.
    ///
    /// The proof demonstrates (in zero knowledge):
    ///   1. Knowledge of private inputs whose Poseidon2 hash = commitment
    ///   2. A valid nullifier derived from (commitment, secret)
    ///
    /// Verification uses Protocol 26 BN254 host functions.
    /// Returns the collateral amount on success.
    pub fn close(
        env: Env,
        trader: Address,
        commitment: BytesN<32>,
        nullifier: BytesN<32>,
        proof: UltraHonkProof,
        public_inputs: Vec<BytesN<32>>,
    ) -> i128 {
        trader.require_auth();

        // 1. Nullifier check — prevents double-spend
        let null_key = DataKey::Nullifier(nullifier.clone());
        if env.storage().persistent().has(&null_key) {
            panic!("position already closed");
        }

        // 2. Commitment must exist and belong to this trader
        let pos_key = DataKey::Position(commitment.clone());
        let pos: Position = env
            .storage()
            .persistent()
            .get(&pos_key)
            .unwrap_or_else(|| panic!("position not found"));
        if pos.trader != trader {
            panic!("unauthorized");
        }

        // 3. UltraHonk proof verification via Protocol 26 BN254 host functions.
        //
        // This is where the UltraHonk verification equation is checked:
        //   e(proof_A, proof_B) * e(VK_alpha, VK_beta) *
        //   e(L_pub, VK_gamma) * e(proof_C, VK_delta) == 1
        //
        // The exact implementation follows the indextree verifier pattern:
        //   1. Parse proof bytes into G1/G2 points
        //   2. Compute L_pub = Σ public_input_i * vk_ic_i via g1_msm
        //   3. Compute pairing_check with 4 pairs
        //
        // For the full UltraHonk verifier implementation, see:
        //   https://github.com/indextree/ultrahonk_soroban_contract
        if !Self::verify_ultrahonk(&env, &proof, &public_inputs) {
            panic!("invalid ZK proof");
        }

        // 4. Commit effects (checks-effects-interactions pattern)
        env.storage().persistent().set(&null_key, &true);
        env.storage().persistent().extend_ttl(&null_key, 17280, 17280);
        env.storage().persistent().remove(&pos_key);

        pos.collateral
    }

    pub fn collateral_of(env: Env, commitment: BytesN<32>) -> Option<i128> {
        env.storage()
            .persistent()
            .get::<_, Position>(&DataKey::Position(commitment))
            .map(|p| p.collateral)
    }

    pub fn is_spent(env: Env, nullifier: BytesN<32>) -> bool {
        env.storage()
            .persistent()
            .has(&DataKey::Nullifier(nullifier))
    }

    // ── UltraHonk Verifier pattern (Protocol 26 BN254) ──────────────
    //
    // The verification equation for Groth16/UltraHonk:
    //   e(A, B) * e(-alpha, beta) * e(-L_pub, gamma) * e(-C, delta) == 1
    //
    // Implemented using three Protocol 26 host functions:
    //   g1_msm → g1_add → pairing_check

    fn verify_ultrahonk(
        env: &Env,
        proof: &UltraHonkProof,
        public_inputs: &Vec<BytesN<32>>,
    ) -> bool {
        let bn = env.crypto().bn254();

        // ── Parse proof points ─────────────────────────────────────
        // In a real implementation, proof.proof_bytes would be deserialized
        // into the specific UltraHonk proof structure (G1/G2 points and
        // field elements). This parsing depends on the bb.js version and
        // UltraHonk protocol version.
        //
        // For reference, the indextree verifier does:
        //   let proof_a = parse_g1(&proof.proof_bytes[0..64]);
        //   let proof_b = parse_g2(&proof.proof_bytes[64..192]);
        //   let proof_c = parse_g1(&proof.proof_bytes[192..256]);

        // For this example, parse the VK G2 points from compile-time constants.
        let vk_beta = Bn254G2Affine::from_bytes(BytesN::from_array(env, &VK_BETA_G2));
        let vk_gamma = Bn254G2Affine::from_bytes(BytesN::from_array(env, &VK_GAMMA_G2));
        let vk_delta = Bn254G2Affine::from_bytes(BytesN::from_array(env, &VK_DELTA_G2));
        let vk_alpha = Bn254G1Affine::from_bytes(BytesN::from_array(env, &VK_ALPHA_G1));

        // ── Compute L_pub via g1_msm ──────────────────────────────
        // L_pub = vk_ic[0] + Σ(public_input_i * vk_ic[i+1])
        let mut ic_points: Vec<Bn254G1Affine> = Vec::new(env);
        let mut scalars: Vec<Bn254Fr> = Vec::new(env);

        for i in 0..public_inputs.len() {
            let ic = match i {
                0 => Bn254G1Affine::from_bytes(BytesN::from_array(env, &VK_IC_1)),
                1 => Bn254G1Affine::from_bytes(BytesN::from_array(env, &VK_IC_2)),
                _ => break,
            };
            ic_points.push_back(ic);
            scalars.push_back(Bn254Fr::from_bytes(public_inputs.get(i).unwrap()));
        }

        let msm_result = bn.g1_msm(ic_points, scalars);
        let ic0 = Bn254G1Affine::from_bytes(BytesN::from_array(env, &VK_IC_0));
        let l_pub = bn.g1_add(&msm_result, &ic0);

        // ── Negate G1 points ───────────────────────────────────────
        // Pairing equation uses negative points.
        let neg_alpha = -&vk_alpha;
        let neg_l_pub = -&l_pub;

        // In a real implementation, proof A and C would be parsed here.
        // let neg_c = -&proof_c;

        // ── Pairing check ──────────────────────────────────────────
        // e(A, B) * e(-alpha, beta) * e(-L_pub, gamma) * e(-C, delta) == 1
        let mut g1: Vec<Bn254G1Affine> = Vec::new(env);
        let mut g2: Vec<Bn254G2Affine> = Vec::new(env);

        // Pair 1: e(A, B) — proof-specific
        // g1.push_back(proof_a);
        // g2.push_back(proof_b);

        // Pair 2: e(-alpha, beta) — VK, fixed for this circuit
        g1.push_back(neg_alpha);
        g2.push_back(vk_beta);

        // Pair 3: e(-L_pub, gamma) — public inputs
        g1.push_back(neg_l_pub);
        g2.push_back(vk_gamma);

        // Pair 4: e(-C, delta) — proof-specific
        // g1.push_back(neg_c);
        // g2.push_back(vk_delta);

        // Protocol 26 native pairing check.
        // For this example with placeholder VKs, always returns false
        // (zero points are not on the BN254 curve).
        // Populate VK_* constants after compiling the circuit to enable
        // real verification.
        bn.pairing_check(g1, g2)
    }
}

#[cfg(test)]
mod test {
    use super::*;
    use soroban_sdk::{testutils::Address as _, Env};

    fn seed(env: &Env, seed: u8) -> BytesN<32> {
        BytesN::from_array(env, &[seed; 32])
    }

    #[test]
    fn test_open_stores_position() {
        let env = Env::default();
        env.mock_all_auths();
        let id = env.register_contract(None, StellarVerifier);
        let client = StellarVerifierClient::new(&env, &id);

        let trader = Address::generate(&env);
        let c = seed(&env, 1);
        client.open(&trader, &c, &1_000_000);
        assert_eq!(client.collateral_of(&c), Some(1_000_000));
    }

    #[test]
    #[should_panic(expected = "commitment already exists")]
    fn test_duplicate_open_rejected() {
        let env = Env::default();
        env.mock_all_auths();
        let id = env.register_contract(None, StellarVerifier);
        let client = StellarVerifierClient::new(&env, &id);

        let trader = Address::generate(&env);
        let c = seed(&env, 1);
        client.open(&trader, &c, &1_000_000);
        client.open(&trader, &c, &500_000);
    }

    #[test]
    fn test_not_spent_initially() {
        let env = Env::default();
        env.mock_all_auths();
        let id = env.register_contract(None, StellarVerifier);
        let client = StellarVerifierClient::new(&env, &id);
        assert!(!client.is_spent(&seed(&env, 2)));
    }
}
