use std::{env, fmt::Write as _, fs, path::PathBuf};

use ark_bn254::{g1::G1Affine, g2::G2Affine};
use ark_ff::{BigInteger, PrimeField};
use num_bigint::BigUint;
use serde_json::Value;

fn main() {
    println!("cargo:rerun-if-env-changed=VERIFIER_VK_JSON");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));

    let path = env::var("VERIFIER_VK_JSON").unwrap_or_default();
    if path.is_empty() {
        write_placeholder_vk(&out_dir);
        return;
    }
    let path = PathBuf::from(&path);
    println!("cargo:rerun-if-changed={}", path.display());
    let json = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read VK file `{}`: {e}", path.display()));
    let content = vk_rs_from_json(&json);
    fs::write(out_dir.join("vk.rs"), content).expect("failed to write vk.rs");
}

fn write_placeholder_vk(out_dir: &PathBuf) {
    let content = "\
pub const VK_ALPHA_G1: [u8; 64] = [0u8; 64];
pub const VK_BETA_G2: [u8; 128] = [0u8; 128];
pub const VK_GAMMA_G2: [u8; 128] = [0u8; 128];
pub const VK_DELTA_G2: [u8; 128] = [0u8; 128];
pub const VK_IC: [[u8; 64]; 1] = [[0u8; 64]];
";
    fs::write(out_dir.join("vk.rs"), content).expect("failed to write placeholder vk.rs");
}

fn bigint_to_be_32<B: BigInteger>(value: B) -> [u8; 32] {
    let bytes = value.to_bytes_be();
    let mut out = [0u8; 32];
    let start = 32usize.saturating_sub(bytes.len());
    out[start..].copy_from_slice(&bytes[..bytes.len().min(32)]);
    out
}

fn g1_to_soroban_bytes(p: &G1Affine) -> [u8; 64] {
    let mut out = [0u8; 64];
    out[..32].copy_from_slice(&bigint_to_be_32(p.x.into_bigint()));
    out[32..].copy_from_slice(&bigint_to_be_32(p.y.into_bigint()));
    out
}

fn g2_to_soroban_bytes(p: &G2Affine) -> [u8; 128] {
    let mut out = [0u8; 128];
    out[..32].copy_from_slice(&bigint_to_be_32(p.x.c1.into_bigint()));
    out[32..64].copy_from_slice(&bigint_to_be_32(p.x.c0.into_bigint()));
    out[64..96].copy_from_slice(&bigint_to_be_32(p.y.c1.into_bigint()));
    out[96..].copy_from_slice(&bigint_to_be_32(p.y.c0.into_bigint()));
    out
}

fn parse_fq_decimal(value: &str) -> Result<ark_bn254::Fq, String> {
    let bigint = BigUint::parse_bytes(value.as_bytes(), 10)
        .ok_or_else(|| format!("invalid decimal field element: {value}"))?;
    Ok(ark_bn254::Fq::from_be_bytes_mod_order(&bigint.to_bytes_be()))
}

fn fq2_from_decimals(c0: &str, c1: &str) -> Result<ark_bn254::Fq2, String> {
    Ok(ark_bn254::Fq2::new(
        parse_fq_decimal(c0)?,
        parse_fq_decimal(c1)?,
    ))
}

fn g1_bytes(pt: &Value) -> [u8; 64] {
    let arr = pt.as_array().expect("G1 point must be a JSON array");
    let x = parse_fq_decimal(arr[0].as_str().expect("G1.x must be a string"))
        .expect("invalid G1.x field element");
    let y = parse_fq_decimal(arr[1].as_str().expect("G1.y must be a string"))
        .expect("invalid G1.y field element");
    g1_to_soroban_bytes(&G1Affine::new_unchecked(x, y))
}

fn g2_bytes(pt: &Value) -> [u8; 128] {
    let arr = pt.as_array().expect("G2 point must be a JSON array");
    let x = arr[0].as_array().expect("G2.x must be a JSON array");
    let y = arr[1].as_array().expect("G2.y must be a JSON array");
    let xf = fq2_from_decimals(
        x[0].as_str().expect("G2.x.c0 must be a string"),
        x[1].as_str().expect("G2.x.c1 must be a string"),
    )
    .expect("invalid G2.x field element");
    let yf = fq2_from_decimals(
        y[0].as_str().expect("G2.y.c0 must be a string"),
        y[1].as_str().expect("G2.y.c1 must be a string"),
    )
    .expect("invalid G2.y field element");
    g2_to_soroban_bytes(&G2Affine::new_unchecked(xf, yf))
}

fn fmt_bytes(bytes: &[u8]) -> String {
    let mut s = String::from("[");
    for (i, b) in bytes.iter().enumerate() {
        if i > 0 {
            s.push(',');
        }
        write!(s, "0x{b:02x}").expect("infallible write to String");
    }
    s.push(']');
    s
}

fn vk_rs_from_json(json: &str) -> String {
    let v: Value = serde_json::from_str(json).expect("VK file is not valid JSON");

    let alpha = g1_bytes(&v["vk_alpha_1"]);
    let beta = g2_bytes(&v["vk_beta_2"]);
    let gamma = g2_bytes(&v["vk_gamma_2"]);
    let delta = g2_bytes(&v["vk_delta_2"]);

    let ic_arr = v["IC"].as_array().expect("IC must be a JSON array");
    let ic_len = ic_arr.len();
    let ic_items: Vec<String> = ic_arr.iter().map(|pt| fmt_bytes(&g1_bytes(pt))).collect();

    let mut out = String::new();
    writeln!(out, "// Auto-generated by build.rs").expect("infallible write to String");
    writeln!(out, "const VK_ALPHA_G1: [u8; 64] = {};", fmt_bytes(&alpha))
        .expect("infallible write to String");
    writeln!(out, "const VK_BETA_G2: [u8; 128] = {};", fmt_bytes(&beta))
        .expect("infallible write to String");
    writeln!(out, "const VK_GAMMA_G2: [u8; 128] = {};", fmt_bytes(&gamma))
        .expect("infallible write to String");
    writeln!(out, "const VK_DELTA_G2: [u8; 128] = {};", fmt_bytes(&delta))
        .expect("infallible write to String");
    writeln!(
        out,
        "const VK_IC: [[u8; 64]; {ic_len}] = [{}];",
        ic_items.join(",")
    )
    .expect("infallible write to String");
    out
}
