#![no_std]

extern crate alloc;

use soroban_sdk::{
    contract, contractimpl, contracttype, vec, Address, Bytes, BytesN, Env, Vec,
    crypto::bn254::{Bn254Fr, Bn254G1Affine as G1Affine, Bn254G2Affine as G2Affine},
};
use tiny_types::Groth16Proof;

include!(concat!(env!("OUT_DIR"), "/sp1_vk.rs"));

#[contracttype]
pub enum DataKey {
    Commitment(BytesN<32>),
    Nullifier(BytesN<32>),
}

#[contracttype]
#[derive(Clone)]
pub struct Note {
    pub amount: i128,
    pub owner: Address,
}

struct Sp1Vk {
    alpha: G1Affine,
    beta: G2Affine,
    gamma: G2Affine,
    delta: G2Affine,
    ic: Vec<G1Affine>,
}

fn load_sp1_vk(env: &Env) -> Sp1Vk {
    let mut ic: Vec<G1Affine> = Vec::new(env);
    for bytes in SP1_VK_IC.iter() {
        ic.push_back(G1Affine::from_bytes(BytesN::from_array(env, bytes)));
    }
    Sp1Vk {
        alpha: G1Affine::from_bytes(BytesN::from_array(env, &SP1_VK_ALPHA_G1)),
        beta: G2Affine::from_bytes(BytesN::from_array(env, &SP1_VK_BETA_G2)),
        gamma: G2Affine::from_bytes(BytesN::from_array(env, &SP1_VK_GAMMA_G2)),
        delta: G2Affine::from_bytes(BytesN::from_array(env, &SP1_VK_DELTA_G2)),
        ic,
    }
}

fn is_placeholder_vk() -> bool {
    SP1_VKEY_HASH == [0u8; 32]
}

#[contract]
pub struct TinyPool;

#[contractimpl]
impl TinyPool {
    /// Deposit: store a UTXO commitment.
    /// For the SP1 path: commitment = SHA256(amount_be || secret_be || 0x01)
    /// For the Circom path: commitment = Poseidon2(amount, secret, domain=1)
    /// The pool stores whichever bytes you give it.
    pub fn deposit(env: Env, owner: Address, commitment: BytesN<32>, amount: i128) {
        owner.require_auth();
        if amount <= 0 {
            panic!("amount must be positive");
        }
        let key = DataKey::Commitment(commitment.clone());
        if env.storage().persistent().has(&key) {
            panic!("commitment already exists");
        }
        env.storage().persistent().set(&key, &Note { amount, owner });
        env.storage().persistent().extend_ttl(&key, 17280, 17280);
    }

    /// Withdraw with SP1 Groth16 proof.
    ///
    /// The proof must have been generated by the private-payment-sp1 SP1 program
    /// proving knowledge of (amount, secret) such that:
    ///   commitment = SHA256(amount_be || secret_be || 0x01)
    ///   nullifier  = SHA256(commitment  || secret_be || 0x02)
    ///
    /// SP1 Groth16 public inputs:
    ///   pi[0] = SP1_VKEY_HASH  (hardcoded: identifies our SP1 program)
    ///   pi[1] = sha256(commitment || nullifier) mod BN254_Fr  (committed values digest)
    pub fn withdraw_sp1(
        env: Env,
        owner: Address,
        commitment: BytesN<32>,
        nullifier: BytesN<32>,
        proof: Groth16Proof,
    ) -> i128 {
        owner.require_auth();

        if !is_placeholder_vk() {
            // Compute committed_values_digest = sha256(commitment || nullifier) mod BN254_Fr
            // SP1 serializes PublicOutput{commitment, nullifier} as 64 raw bytes (bincode fixed arrays)
            // hash_bn254() in SP1 masks the top 3 bits so the result fits in BN254 Fr
            let mut pub_bytes = Bytes::new(&env);
            pub_bytes.extend_from_array::<32>(&commitment.to_array());
            pub_bytes.extend_from_array::<32>(&nullifier.to_array());
            let sha: BytesN<32> = env.crypto().sha256(&pub_bytes).into();
            let mut sha_arr = sha.to_array();
            sha_arr[0] &= 0b00011111; // mask top 3 bits (matches SP1's hash_bn254)
            let digest = Bn254Fr::from_bytes(BytesN::from_array(&env, &sha_arr));

            let vkey_hash = Bn254Fr::from_bytes(BytesN::from_array(&env, &SP1_VKEY_HASH));
            let vk_root = Bn254Fr::from_bytes(BytesN::from_array(&env, &SP1_VK_ROOT));

            let vk = load_sp1_vk(&env);
            let bn = env.crypto().bn254();

            // SP1 Groth16 has 5 public inputs: [vkey_hash, digest, exit_code, vk_root, proof_nonce]
            // For local proofs: exit_code=0, proof_nonce=0 → IC[3] and IC[5] terms vanish
            // vk_x = IC[0] + IC[1]*vkey_hash + IC[2]*digest + IC[4]*vk_root
            let mut vk_x = vk.ic.get(0).unwrap();
            vk_x = bn.g1_add(&vk_x, &bn.g1_mul(&vk.ic.get(1).unwrap(), &vkey_hash));
            vk_x = bn.g1_add(&vk_x, &bn.g1_mul(&vk.ic.get(2).unwrap(), &digest));
            vk_x = bn.g1_add(&vk_x, &bn.g1_mul(&vk.ic.get(4).unwrap(), &vk_root));

            let neg_a = -proof.a.clone();
            let g1_points = vec![&env, neg_a, vk.alpha, vk_x, proof.c.clone()];
            let g2_points = vec![&env, proof.b.clone(), vk.beta, vk.gamma, vk.delta];

            if !bn.pairing_check(g1_points, g2_points) {
                panic!("invalid SP1 proof");
            }
        }

        let null_key = DataKey::Nullifier(nullifier.clone());
        if env.storage().persistent().has(&null_key) {
            panic!("already spent");
        }

        let pos_key = DataKey::Commitment(commitment.clone());
        let note: Note = env
            .storage()
            .persistent()
            .get(&pos_key)
            .unwrap_or_else(|| panic!("commitment not found"));
        if note.owner != owner {
            panic!("unauthorized");
        }

        env.storage().persistent().set(&null_key, &true);
        env.storage().persistent().extend_ttl(&null_key, 17280, 17280);
        env.storage().persistent().remove(&pos_key);

        note.amount
    }

    /// Withdraw without proof (legacy path — ZK not enforced).
    pub fn withdraw(
        env: Env,
        owner: Address,
        commitment: BytesN<32>,
        nullifier: BytesN<32>,
    ) -> i128 {
        owner.require_auth();

        let null_key = DataKey::Nullifier(nullifier.clone());
        if env.storage().persistent().has(&null_key) {
            panic!("already spent");
        }

        let pos_key = DataKey::Commitment(commitment.clone());
        let note: Note = env
            .storage()
            .persistent()
            .get(&pos_key)
            .unwrap_or_else(|| panic!("commitment not found"));
        if note.owner != owner {
            panic!("unauthorized");
        }

        env.storage().persistent().set(&null_key, &true);
        env.storage().persistent().extend_ttl(&null_key, 17280, 17280);
        env.storage().persistent().remove(&pos_key);

        note.amount
    }

    pub fn balance_of(env: Env, commitment: BytesN<32>) -> Option<i128> {
        env.storage()
            .persistent()
            .get::<_, Note>(&DataKey::Commitment(commitment))
            .map(|n| n.amount)
    }

    pub fn is_spent(env: Env, nullifier: BytesN<32>) -> bool {
        env.storage()
            .persistent()
            .has(&DataKey::Nullifier(nullifier))
    }
}

#[cfg(test)]
mod test {
    use super::*;
    use soroban_sdk::{testutils::Address as _, Env};

    fn seed(env: &Env, v: u8) -> BytesN<32> {
        BytesN::from_array(env, &[v; 32])
    }

    #[test]
    fn test_deposit_stores_note() {
        let env = Env::default();
        env.mock_all_auths();
        let id = env.register_contract(None, TinyPool);
        let client = TinyPoolClient::new(&env, &id);

        let owner = Address::generate(&env);
        let c = seed(&env, 1);
        client.deposit(&owner, &c, &1_000_000);
        assert_eq!(client.balance_of(&c), Some(1_000_000));
    }

    #[test]
    #[should_panic(expected = "commitment already exists")]
    fn test_duplicate_deposit_rejected() {
        let env = Env::default();
        env.mock_all_auths();
        let id = env.register_contract(None, TinyPool);
        let client = TinyPoolClient::new(&env, &id);

        let owner = Address::generate(&env);
        let c = seed(&env, 1);
        client.deposit(&owner, &c, &1_000_000);
        client.deposit(&owner, &c, &500_000);
    }

    #[test]
    fn test_withdraw_sp1_placeholder_vk() {
        // When SP1 VK is placeholder (zeros), pairing check is skipped
        // (placeholder mode for development without real SP1 setup)
        assert!(is_placeholder_vk(), "this test requires placeholder VK build");

        let env = Env::default();
        env.mock_all_auths();
        let id = env.register_contract(None, TinyPool);
        let client = TinyPoolClient::new(&env, &id);

        let owner = Address::generate(&env);
        let commitment = seed(&env, 0xAB);
        let nullifier = seed(&env, 0xCD);

        client.deposit(&owner, &commitment, &5_000_000);

        let zero_g1 = BytesN::from_array(&env, &[0u8; 64]);
        let zero_g2 = BytesN::from_array(&env, &[0u8; 128]);
        let proof = Groth16Proof {
            a: soroban_sdk::crypto::bn254::Bn254G1Affine::from_bytes(zero_g1),
            b: soroban_sdk::crypto::bn254::Bn254G2Affine::from_bytes(zero_g2),
            c: soroban_sdk::crypto::bn254::Bn254G1Affine::from_bytes(
                BytesN::from_array(&env, &[0u8; 64]),
            ),
        };

        let amount = client.withdraw_sp1(&owner, &commitment, &nullifier, &proof);
        assert_eq!(amount, 5_000_000);
        assert!(client.is_spent(&nullifier));
    }
}
