use std::{env, fmt::Write as _, fs, path::PathBuf};

use serde_json::Value;

fn main() {
    println!("cargo:rerun-if-env-changed=VK_COMMIT_JSON");
    println!("cargo:rerun-if-env-changed=VK_CANCEL_JSON");
    println!("cargo:rerun-if-env-changed=VK_MATCH_JSON");
    println!("cargo:rerun-if-env-changed=VK_NOTE_SPEND_JSON");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));

    let keys_fallback = || -> PathBuf {
        let m = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        let candidate = m.join("../../circuits/keys");
        fs::canonicalize(&candidate).unwrap_or_else(|e| {
            panic!(
                "build.rs: cannot find circuits/keys directory at `{}`: {e}\n\
                 Run `cargo run -p rust-circuits -- setup` to generate VK files,\n\
                 or set VK_COMMIT_JSON / VK_CANCEL_JSON / VK_MATCH_JSON / VK_NOTE_SPEND_JSON.",
                candidate.display()
            )
        })
    };

    let resolve = |env_var: &str, filename: &str| -> String {
        env::var(env_var)
            .unwrap_or_else(|_| keys_fallback().join(filename).to_string_lossy().to_string())
    };

    let commit_path = resolve("VK_COMMIT_JSON", "order_commitment_vk.json");
    let cancel_path = resolve("VK_CANCEL_JSON", "order_cancel_vk.json");
    let match_path = resolve("VK_MATCH_JSON", "order_match_vk.json");
    let note_spend_path = resolve("VK_NOTE_SPEND_JSON", "note_spend_vk.json");

    // Re-run build script if the VK JSON files change on disk
    println!("cargo:rerun-if-changed={}", commit_path);
    println!("cargo:rerun-if-changed={}", cancel_path);
    println!("cargo:rerun-if-changed={}", match_path);
    println!("cargo:rerun-if-changed={}", note_spend_path);

    let commit_vk = read_vk_json(&commit_path);
    let cancel_vk = read_vk_json(&cancel_path);
    let match_vk = read_vk_json(&match_path);
    let note_spend_vk = read_vk_json(&note_spend_path);

    let mut content = String::new();
    writeln!(content, "// Auto-generated by orderbook build.rs").unwrap();

    // Use match VK for alpha/beta/gamma/delta
    writeln!(
        content,
        "const VK_ALPHA_G1: [u8; 64] = {};",
        fmt_bytes(&g1_bytes(&match_vk["vk_alpha_1"]))
    )
    .unwrap();
    writeln!(
        content,
        "const VK_BETA_G2: [u8; 128] = {};",
        fmt_bytes(&g2_bytes(&match_vk["vk_beta_2"]))
    )
    .unwrap();
    writeln!(
        content,
        "const VK_GAMMA_G2: [u8; 128] = {};",
        fmt_bytes(&g2_bytes(&match_vk["vk_gamma_2"]))
    )
    .unwrap();
    writeln!(
        content,
        "const VK_DELTA_G2: [u8; 128] = {};",
        fmt_bytes(&g2_bytes(&match_vk["vk_delta_2"]))
    )
    .unwrap();

    let commit_ic = ic_items(&commit_vk);
    writeln!(
        content,
        "const VK_COMMIT_IC: [[u8; 64]; {}] = [{}];",
        commit_ic.len(),
        commit_ic.join(",")
    )
    .unwrap();

    let cancel_ic = ic_items(&cancel_vk);
    writeln!(
        content,
        "const VK_CANCEL_IC: [[u8; 64]; {}] = [{}];",
        cancel_ic.len(),
        cancel_ic.join(",")
    )
    .unwrap();

    let match_ic = ic_items(&match_vk);
    writeln!(
        content,
        "const VK_MATCH_IC: [[u8; 64]; {}] = [{}];",
        match_ic.len(),
        match_ic.join(",")
    )
    .unwrap();

    let note_spend_ic = ic_items(&note_spend_vk);
    writeln!(
        content,
        "const VK_NOTE_SPEND_IC: [[u8; 64]; {}] = [{}];",
        note_spend_ic.len(),
        note_spend_ic.join(",")
    )
    .unwrap();

    fs::write(out_dir.join("vk.rs"), content).expect("failed to write vk.rs");
}

fn read_vk_json(path: &str) -> Value {
    let data =
        fs::read_to_string(path).unwrap_or_else(|e| panic!("failed to read VK file `{path}`: {e}"));
    serde_json::from_str(&data).expect("VK file is not valid JSON")
}

fn ic_items(vk: &Value) -> Vec<String> {
    vk["IC"]
        .as_array()
        .expect("IC must be a JSON array")
        .iter()
        .map(|pt| fmt_bytes(&g1_bytes(pt)))
        .collect()
}

fn fmt_bytes(bytes: &[u8]) -> String {
    let mut s = String::from("[");
    for (i, b) in bytes.iter().enumerate() {
        if i > 0 {
            s.push(',');
        }
        write!(s, "0x{b:02x}").unwrap();
    }
    s.push(']');
    s
}

fn g1_bytes(pt: &Value) -> [u8; 64] {
    let arr = pt.as_array().expect("G1 point must be a JSON array");
    let x: num_bigint::BigUint = arr[0]
        .as_str()
        .expect("x must be string")
        .parse()
        .expect("invalid x");
    let y: num_bigint::BigUint = arr[1]
        .as_str()
        .expect("y must be string")
        .parse()
        .expect("invalid y");
    let mut out = [0u8; 64];
    let xb = to_be_32(&x);
    let yb = to_be_32(&y);
    out[..32].copy_from_slice(&xb);
    out[32..].copy_from_slice(&yb);
    out
}

fn g2_bytes(pt: &Value) -> [u8; 128] {
    let arr = pt.as_array().expect("G2 point must be a JSON array");
    let x = arr[0].as_array().expect("G2.x must be array");
    let y = arr[1].as_array().expect("G2.y must be array");
    // snarkjs JSON: [x_c0, x_c1], [y_c0, y_c1]
    // Soroban/SDK encoding: x.c1 || x.c0 || y.c1 || y.c0
    let x_c0: num_bigint::BigUint = x[0]
        .as_str()
        .expect("x_c0 must be a string")
        .parse()
        .expect("invalid x_c0");
    let x_c1: num_bigint::BigUint = x[1]
        .as_str()
        .expect("x_c1 must be a string")
        .parse()
        .expect("invalid x_c1");
    let y_c0: num_bigint::BigUint = y[0]
        .as_str()
        .expect("y_c0 must be a string")
        .parse()
        .expect("invalid y_c0");
    let y_c1: num_bigint::BigUint = y[1]
        .as_str()
        .expect("y_c1 must be a string")
        .parse()
        .expect("invalid y_c1");
    let mut out = [0u8; 128];
    out[..32].copy_from_slice(&to_be_32(&x_c1));
    out[32..64].copy_from_slice(&to_be_32(&x_c0));
    out[64..96].copy_from_slice(&to_be_32(&y_c1));
    out[96..].copy_from_slice(&to_be_32(&y_c0));
    out
}

fn to_be_32(n: &num_bigint::BigUint) -> [u8; 32] {
    let bytes = n.to_bytes_be();
    let mut out = [0u8; 32];
    let start = 32usize.saturating_sub(bytes.len());
    out[start..].copy_from_slice(&bytes[..bytes.len().min(32)]);
    out
}
